buildscript {
    ext.kotlin_version = '1.9.0'
    
    // I repository qui dentro servono SOLO a scaricare il plugin Gradle e Kotlin
    repositories { 
        google() 
        mavenCentral() 
    }
    
    dependencies {
        classpath 'com.android.tools.build:gradle:8.2.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

// Allprojects rimane privo di repository per rispettare settings.gradle
allprojects {
    // Lascia vuoto o inserisci altre configurazioni non correlate ai repository
}

task clean(type: Delete) { 
    delete rootProject.buildDir 
}
